import { v4 as uuidv4 } from "uuid";

const employeeList = [
    {
        emp_name: "Alnas Kabeer",
        emp_id: uuidv4(),
        emp_join: "12.04.2021",
        emp_role: "Developer",
        emp_status: "Active",
        emp_exp: "5",
        emp_addr: "Alnaskabeer.address where he lives",
        emp_dept: "Engineering",
    },
    {
        emp_name: "John Cena",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Designer",
        emp_status: "Active",
        emp_exp: "3",
        emp_addr: "You can't see him",
        emp_dept: "Security",
    },
    {
        emp_name: "Bill Gaytes",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Tester",
        emp_status: "Inactive",
        emp_exp: "2",
        emp_addr: "You can see him",
        emp_dept: "HR",
    },
    {
        emp_name: "John Cena",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Designer",
        emp_status: "Active",
        emp_exp: "3",
        emp_addr: "You can't see him",
        emp_dept: "Security",
    },
    {
        emp_name: "Bill Gaytes",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Tester",
        emp_status: "Inactive",
        emp_exp: "2",
        emp_addr: "You can see him",
        emp_dept: "HR",
    },
    {
        emp_name: "John Cena",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Designer",
        emp_status: "Probation",
        emp_exp: "3",
        emp_addr: "You can't see him",
        emp_dept: "Security",
    },
    {
        emp_name: "Bill Gaytes",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Tester",
        emp_status: "Inactive",
        emp_exp: "2",
        emp_addr: "You can see him",
        emp_dept: "HR",
    },
    {
        emp_name: "John Cena",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Designer",
        emp_status: "Probation",
        emp_exp: "3",
        emp_addr: "You can't see him",
        emp_dept: "Security",
    },
    {
        emp_name: "Bill Gaytes",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Tester",
        emp_status: "Inactive",
        emp_exp: "2",
        emp_addr: "You can see him",
        emp_dept: "HR",
    },
    {
        emp_name: "John Cena",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Designer",
        emp_status: "Probation",
        emp_exp: "3",
        emp_addr: "You can't see him",
        emp_dept: "Security",
    },
    {
        emp_name: "Bill Gaytes",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Tester",
        emp_status: "Inactive",
        emp_exp: "2",
        emp_addr: "You can see him",
        emp_dept: "HR",
    },
    {
        emp_name: "John Cena",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Designer",
        emp_status: "Probation",
        emp_exp: "3",
        emp_addr: "You can't see him",
        emp_dept: "Security",
    },
    {
        emp_name: "Bill Gaytes",
        emp_id: uuidv4(),
        emp_join: "13.04.2021",
        emp_role: "Tester",
        emp_status: "Inactive",
        emp_exp: "2",
        emp_addr: "You can see him",
        emp_dept: "HR",
    },
];

export default employeeList;
